name: JSON to JSTAR Playlist

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    # ⏰ Runs 3 times a day (every 8 hours)
    - cron: "0 */8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build playlist from JSON secret
        shell: bash
        env:
          SRC: ${{ secrets.d }}
        run: |
          set -e

          OUTPUT="playlist.m3u"
          JSON="channels.json"

          echo "#EXTM3U" > "$OUTPUT"

          # Fetch JSON (valid array)
          curl -fsSL "$SRC" -o "$JSON"

          # Convert JSON → JSTAR M3U
          jq -c '.[]' "$JSON" | while read -r ch; do
            id=$(jq -r '.channel_id' <<< "$ch")
            name=$(jq -r '.channel_name' <<< "$ch")
            group=$(jq -r '.channel_genre // "Jiostar"' <<< "$ch")
            logo=$(jq -r '.channel_logo' <<< "$ch")
            url=$(jq -r '.channel_url' <<< "$ch")
            kid=$(jq -r '.keyId' <<< "$ch")
            key=$(jq -r '.key' <<< "$ch")
            ua=$(jq -r '.UserAgent // "plaYtv/7.1.3 (Linux;Android 13)"' <<< "$ch")

           echo "#EXTINF:-1 tvg-id=\"$id\" group-title=\"$group\" tvg-logo=\"$logo\",$name" >> "$OUTPUT"
           echo "#KODIPROP:inputstream.adaptive.license_type=clearkey" >> "$OUTPUT"
           echo "#KODIPROP:inputstream.adaptive.license_key=$kid:$key" >> "$OUTPUT"
           echo "#EXTHTTP:$url" >> "$OUTPUT"
           echo "" >> "$OUTPUT"
          done

      - name: Commit and push playlist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "Auto update playlist (3x daily)" || echo "No changes"
          git push
